# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

addons:
  apt:
    packages:
      - python2.7
      - python-numpy
before_install:
  - pip install --user numpy
  - pip install --user pandas

